

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/coloringBox")
@TestDataPath("$PROJECT_ROOT")
public class ColoringBoxTestGenerated extends AbstractColoringBoxTest {
  @Test
  public void testAllFilesPresentInColoringBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/coloringBox"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("classWithFields.kt")
  public void testClassWithFields() {
    runTest("src/testData/coloringBox/classWithFields.kt");
  }

  @Test
  @TestMetadata("defaultValuesInConstructor.kt")
  public void testDefaultValuesInConstructor() {
    runTest("src/testData/coloringBox/defaultValuesInConstructor.kt");
  }

  @Test
  @TestMetadata("finalClass.kt")
  public void testFinalClass() {
    runTest("src/testData/coloringBox/finalClass.kt");
  }

  @Test
  @TestMetadata("functionWithContext.kt")
  public void testFunctionWithContext() {
    runTest("src/testData/coloringBox/functionWithContext.kt");
  }

  @Test
  @TestMetadata("noDefaultConstructor.kt")
  public void testNoDefaultConstructor() {
    runTest("src/testData/coloringBox/noDefaultConstructor.kt");
  }

  @Test
  @TestMetadata("severalConstructors.kt")
  public void testSeveralConstructors() {
    runTest("src/testData/coloringBox/severalConstructors.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("src/testData/coloringBox/simple.kt");
  }
}
